# Generated by Django 3.2.9 on 2021-12-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdata',
            options={'verbose_name': 'StudentData', 'verbose_name_plural': 'Student Data'},
        ),
        migrations.AlterModelTable(
            name='studentdata',
            table='StudentData',
        ),
    ]
