# Generated by Django 3.2.9 on 2021-12-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20211207_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdata',
            options={'verbose_name': 'studentdata', 'verbose_name_plural': 'Student Data'},
        ),
        migrations.AlterModelTable(
            name='studentdata',
            table='studentdata',
        ),
    ]
