# Generated by Django 3.2.9 on 2021-12-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0003_auto_20211212_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'orthers')], max_length=50),
        ),
    ]
