# Generated by Django 3.2.9 on 2021-12-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0007_alter_studentdata_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.AutoField(primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=50)),
            ],
        ),
    ]
